### ISSUE TITLE
Python implementation?

### ISSUE THREAD

**Issue by jpetrucciani** [cvoege/canvas-pong#1] opened 2018-10-15 16:40 UTC
You should probably reimplement this in a better language, like C or Python

**Comment by balderfer** [comment] 2018-10-15 16:41
I agree with what @jpetrucciani has said above. It seems to me that the current implementation in JavaScript is preventing this project from success.

**Comment by benaduggan** [comment] 2018-10-15 16:42
I think it might be smart to move away from using all Microsoft technologies. I'm not sure I believe in their commitment to open source to continue in the future.

**Comment by balderfer** [comment] 2018-10-15 16:44
It should also be noted that Oracle owns the trademark for JavaScript... avoiding using this technology now could save use millions down the road in legal fees.

**Comment by cgaeta** [comment] 2018-10-15 19:33
Embrace the chaos: reimplement in LOLCODE.

**Comment by wuz** [comment] 2018-10-15 19:49
I have to agree here. As a front-end dev, I believe we should be focusing on futuristic technologies - something like COBOL or FORTRAN. Javascript is just too confined for what this could project truly could be.

**Comment by EverettBerry** [comment] 2018-10-15 20:13
Hey guys just gonna hop on this thread with a related problem. When I run `python3 Game.ts` nothing happens. Any ideas?

**Comment by wuz** [comment] 2018-10-15 20:15
@EverettBerry, that's a bit off topic for this discussion. Could you make another issue for that so it can be tracked properly?

**Comment by jpetrucciani** [comment] 2018-10-15 20:16
Now that you mention it @EverettBerry, when I run `python3 Game.ts`, I get the following:
```
  File "Game.ts", line 1
    import {
           ^
SyntaxError: invalid syntax
```

**Comment by wuz** [comment] 2018-10-15 20:17
@jpetrucciani, this seems to be a problem with python not supporting the `{` - I believe there is a work around in just deleting the brackets, but I'm not sure. As I mentioned to @EverettBerry, I'd recommend putting this in a different issue to make sure it get's noticed.

**Comment by balderfer** [comment] 2018-10-15 20:18
Looks like a `.ts` file is actually a typescript file. Try using this cool tool to get it working in python: https://pypi.org/project/dukpy/

**Comment by EverettBerry** [comment] 2018-10-15 20:23
@wuz how do I open a new issue? Anyway here's a screenshot of my terminal.

![image](https://user-images.githubusercontent.com/3907080/46976160-a82d1a00-d096-11e8-8dd3-362b3a18a01c.png)

**Comment by wuz** [comment] 2018-10-15 20:27
@EverettBerry, looks like we could set up a way for you to email in a new issue with this? https://zapier.com/apps/email/integrations/github. I feel like that is probably the easiest way. RE: your screenshot, I think we need more information than that - can you show us the output of you running `system_profiler` and also, for good measure the output of `ps aux`? That should be a good start for us to figure out what is going on.

**Comment by jpetrucciani** [comment] 2018-10-15 20:28
![image](https://user-images.githubusercontent.com/8117202/46976393-66e93a00-d097-11e8-99db-4f8928fb4f08.png)

**Comment by balderfer** [comment] 2018-10-15 20:35
> image

**Comment by balderfer** [comment] 2018-10-15 20:36
> image

You might want to check with your sysadmin, something is not quite right here.

**Comment by jpetrucciani** [comment] 2018-10-15 20:52
@wuz After running `sed -i 's#[{};]##g' *.ts` in the `src/` directory to remove all semicolons and squiggly brackets, running `python3 app.ts` now gives the following:
```
  File "app.ts", line 1
    import  start  from './Game'
                      ^
SyntaxError: invalid syntax
```

**Comment by balderfer** [comment] 2018-10-15 21:09
Duplicate of #1

**Comment by balderfer** [comment] 2018-10-16 17:10
BUMP

**Comment by jpetrucciani** [comment] 2018-10-16 19:53
@cvoege can we have a response to our issues here?

**Comment by cvoege** [comment] 2019-11-14 20:32
@jpetrucciani no u

**Closed as completed by cvoege** 2019-11-14 20:32 UTC
